apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-pipeline
  template:
    metadata:
      labels:
        app: mlops-pipeline
    spec:
      containers:
      - name: mlops-pipeline
        image: mlops-pipeline:latest
        imagePullPolicy: Never  
        ports:
        - containerPort: 80